### ISSUE TITLE
Broken link in using-external-javascript-libraries-in-apache-royale article

### ISSUE THREAD

**Issue by cristallium** [apache/royale-website#5]
Hi 
On article using-external-javascript-libraries-in-apache-royale :
https://royale.apache.org/using-external-javascript-libraries-in-apache-royale/

link

https://github.com/apache/royale-asjs/blob/develop/frameworks/projects/Jewel/src/main/royale/hljs.as

is broken

**Comment by carlosrovira** [comment]
Thanks Fred,

The right link now is: https://github.com/apache/royale-asjs/blob/develop/examples/royale/TourDeJewel/src/main/royale/hljs.as

When I did this tutorial we need that class be in a library due to a compiler bug, but was not really part of Jewel, it was related to TDJ example. Now it's in the right place that is the example.

I fixed that link in pre site and will be uploading soon to public.
